# Generated by Django 4.2.5 on 2023-11-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_vote_alter_community_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='communities/logo'),
        ),
        migrations.AlterField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='communities/banner'),
        ),
    ]
